#spring
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.146.132:8000/demo-spring-boot-mybatis-plus?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password: 11111

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    url: dbc:jtds:sybase://192.168.146.132:8000/testdb;charset=cp936
    username: sa
    password: myPassword

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl