server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    driverClassName: net.sourceforge.jtds.jdbc.Driver
    url: dbc:jtds:sybase://192.168.146.132:8000/testdb
    username: sa
    password: myPassword
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0