server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 使用druid数据源
    driverClassName: net.sourceforge.jtds.jdbc.Driver
    url: jdbc:jtds:sybase://192.168.146.132:8000/testdb;charset=cp936
    username: sa
    password: myPassword
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  #xml文件路径，多个路径有xml文件用逗号分隔
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.example.domain.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #配置这个 会把输出执行的SQL