# ????????????postgres???
# ????????
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.driver-class-name=net.sourceforge.jtds.jdbc.Driver
spring.datasource.url=jdbc:jtds:sybase://192.168.146.132:8000/testdb;charset=cp936
spring.datasource.username=sa
spring.datasource.password=myPassword


# ???????????????????????
# ???????????
spring.datasource.initialSize=5
spring.datasource.minIdle=5
spring.datasource.maxActive=20
# ?????????????
spring.datasource.maxWait=60000
# ???????????????????????????????
spring.datasource.timeBetweenEvictionRunsMillis=60000
# ??????????????????????
spring.datasource.minEvictableIdleTimeMillis=300000
# Oracle???select 1 from dual
spring.datasource.validationQuery=SELECT 'x'
spring.datasource.testWhileIdle=true
spring.datasource.testOnBorrow=false
spring.datasource.testOnReturn=false
# ??PSCache??????????PSCache???
spring.datasource.poolPreparedStatements=true
spring.datasource.maxPoolPreparedStatementPerConnectionSize=20
# ?????????filters????????sql?????'wall'?????
spring.datasource.filters=stat,wall,slf4j
# ??connectProperties?????mergeSql????SQL??
#spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
# ????DruidDataSource?????
#spring.datasource.useGlobalDataSourceStat=true


#mybatis
mybatis.mapper-locations = classpath:mapper/*Mapper.xml
mybatis.config-location = classpath:sqlMapConfig.xml
mybatis.type-aliases-package = com.example.springbootcloud.model