#?????
jdbc.driverClassName=net.sourceforge.jtds.jdbc.Driver
jdbc.url=jdbc:jtds:sybase://192.168.146.132:8000/testdb;charset=cp936
jdbc.username=sa
jdbc.password=myPassword
#??Mapper??
mapper.plugin=tk.mybatis.mapper.generator.MapperPlugin
mapper.Mapper=com.example.demo.common.MySqlExtensionMapper
targetModelPackage=org.example.entity
targetMapperPackage=org.example.mapper