spring:
  application:
    name: mybatis-demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # HikariDataSource 不支持 net.sourceforge.jtds.jdbc.Driver
#    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    #jdbc-url: jdbc:jtds:sybase://192.168.146.132:8000/testdb2;charset=cp936
    driver-class-name: com.sybase.jdbc4.jdbc.SybDriver
    jdbc-url: jdbc:sybase:Tds:192.168.146.132:8000/testdb2;charset=cp936
    username: sa
    password: myPassword

    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

logging:
  config: classpath:logback-spring.xml

mybatis:
  type-aliases-package: org.example.mapper
  mapper-locations: classpath:mapper/**/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出日志